<?php

return [
    "titolo" => "Cookie Policy",
    "testo" => "The website!",
    "testo_2" => "uses technical cookies to ensure the proper functioning of procedures and improve the user experience of online applications. This document provides information on the use of cookies and similar technologies, how they are used by the site, and how to manage them. Cookies are small text files that the sites visited by users send to their devices, where they are stored and then retransmitted to the same sites on subsequent visits. 'Third-party' cookies, on the other hand, are set by a website other than the one the user is visiting. This is because each site can contain elements (images, maps, sounds, specific links to web pages of other domains, etc.) that reside on servers other than the site being visited.",
    "testo_3" => "Types of cookies",
    "testo_4" => "Based on the characteristics and use of cookies, different categories can be distinguished:",
    "testo_5" => "Technical cookies",
    "testo_6" => "Technical cookies are those used solely to \"transmit a communication over an electronic communications network, or to the extent strictly necessary for the provider of an information society service explicitly requested by the subscriber or user to provide such a service\" (see art. 122, paragraph 1, of the Code). They are not used for further purposes and are normally installed directly by the website owner or manager. They can be divided into navigation or session cookies, which ensure the normal navigation and use of the website; analytics cookies, similar to technical cookies when used directly by the site manager to collect information, in aggregate form, on the number of users and how they visit the site; functionality cookies, which allow the user to navigate based on a series of selected criteria to improve the service provided. For the installation of these cookies, the prior consent of users is not required, while the obligation to provide information pursuant to art. 13 of the Code, which the site manager, if only these devices are used, may provide in the manner deemed most appropriate, remains in force.",
    "testo_7" => "Profiling cookies",
    "testo_8" => "Profiling cookies are used to create user profiles and are used to send advertising messages in line with the preferences expressed by the user during navigation. Due to the particular invasiveness these devices can have in the user's private sphere, European and Italian regulations require that the user be adequately informed about their use and give their valid consent. This is referred to in art. 122 of the Code, which states that \"storage of information on a contractor's or user's terminal device or access to information already stored is only permitted on the condition that the contractor or user has given consent after being informed in the simplified manner referred to in Article 13, paragraph 3\" (art. 122, paragraph 1, of the Code). This site does not use profiling cookies.",
    "testo_9" => "Only to monitor and improve the site's performance, we use a market statistical analysis product for detecting site access. It may use cookies, both permanent and non-permanent, to collect statistical information and on the site's \"unique visitors.\" The cookies, defined as \"Unique Visitor Cookies,\" contain an alphanumeric code that identifies browsing computers, without collecting any personal data.",
    "testo_10" => "Cookie Duration",
    "testo_11" => "Some cookies (session cookies) remain active only until the browser is closed or until a logout command is executed. Other cookies \"survive\" the closing of the browser and are available during subsequent visits by the user. These cookies are called persistent, and their duration is set by the server at the time of their creation. In some cases, an expiration date is set, while in other cases, the duration is unlimited.",
    "testo_12" => "Cookie Management",
    "testo_13" => "The user can decide whether to accept cookies or not by using their browser settings. Warning: disabling technical cookies completely or partially may compromise optimal use of the site. Disabling \"third-party\" cookies does not affect navigation. The setting can be defined specifically for different sites and web applications. Additionally, browsers allow defining different settings for \"first-party\" cookies and for \"third-party\" cookies. This site may incorporate scripts in the form of buttons or plugins to facilitate sharing on social networks. This site is an intermediary for third-party cookies over which it has no control, so it is necessary for the user to consult privacy policies directly on the reference sites of the companies providing these services.",
    "testo_14" => "By way of example, here are some links:"
];