<?php

return [
    "titolo" => "Politique relative aux cookies",
    "testo" => "Le site web !",
    "testo_2" => "utilise des cookies techniques pour garantir le bon fonctionnement des procédures et améliorer l'expérience d'utilisation des applications en ligne. Le présent document fournit des informations sur l'utilisation des cookies et des technologies similaires, sur la manière dont ils sont utilisés par le site et comment les gérer. Les cookies sont de petits fichiers texte que les sites visités par les utilisateurs envoient à leurs terminaux, où ils sont stockés pour être ensuite renvoyés aux mêmes sites lors de la visite suivante. Les cookies dits de 'tiers' sont, quant à eux, configurés par un site web différent de celui que l'utilisateur est en train de visiter. Cela est dû au fait que chaque site peut contenir des éléments (images, cartes, sons, liens spécifiques vers des pages web d'autres domaines, etc.) qui résident sur des serveurs différents de celui du site visité.",
    "testo_3" => "Types de cookies",
    "testo_4" => "En fonction des caractéristiques et de l'utilisation des cookies, plusieurs catégories peuvent être distinguées :",
    "testo_5" => "Cookies techniques",
    "testo_6" => "Les cookies techniques sont ceux utilisés uniquement pour \"effectuer la transmission d'une communication sur un réseau de communication électronique, ou dans la mesure strictement nécessaire au fournisseur d'un service de la société de l'information explicitement demandé par l'abonné ou l'utilisateur à fournir ce service\" (cf. art. 122, alinéa 1, du Code). Ils ne sont pas utilisés à d'autres fins et sont normalement installés directement par le titulaire ou le gestionnaire du site web. Ils peuvent être divisés en cookies de navigation ou de session, qui garantissent la navigation normale et l'utilisation du site web ; cookies analytics, assimilés aux cookies techniques lorsqu'ils sont utilisés directement par le gestionnaire du site pour recueillir des informations, de manière agrégée, sur le nombre d'utilisateurs et comment ils visitent le site ; cookies de fonctionnalité, qui permettent à l'utilisateur de naviguer en fonction d'une série de critères sélectionnés afin d'améliorer le service fourni. Pour l'installation de ces cookies, le consentement préalable des utilisateurs n'est pas requis, tandis que l'obligation de fournir des informations conformément à l'art. 13 du Code, que le gestionnaire du site, s'il utilise uniquement ces dispositifs, pourra fournir de la manière qu'il juge la plus appropriée, reste en vigueur.",
    "testo_7" => "Cookies de profilage",
    "testo_8" => "Les cookies de profilage ont pour but de créer des profils relatifs à l'utilisateur et sont utilisés pour envoyer des messages publicitaires en ligne avec les préférences exprimées par celui-ci lors de la navigation. En raison de la particularité intrusive que ces dispositifs peuvent avoir dans la sphère privée des utilisateurs, la réglementation européenne et italienne prévoit que l'utilisateur doit être correctement informé de leur utilisation et donner ainsi son consentement valable. Il est fait référence à l'art. 122 du Code qui prévoit que \"le stockage d'informations sur l'appareil terminal d'un contractant ou d'un utilisateur ou l'accès à des informations déjà stockées ne sont autorisés que si le contractant ou l'utilisateur a donné son consentement après avoir été informé selon les modalités simplifiées prévues à l'article 13, alinéa 3\" (art. 122, alinéa 1, du Code). Le présent site n'utilise pas de cookies de profilage.",
    "testo_9" => "Uniquement pour surveiller et améliorer les performances du site, nous utilisons un produit d'analyse statistique pour la détection des accès au site. Il peut utiliser des cookies, permanents ou non, afin de recueillir des informations statistiques et sur les \"visiteurs uniques\" du site. Les cookies, appelés \"Cookies Visiteur Unique\", contiennent un code alphanumérique qui identifie les ordinateurs de navigation, sans collecte de données personnelles.",
    "testo_10" => "Durée des cookies",
    "testo_11" => "Certains cookies (cookies de session) restent actifs uniquement jusqu'à la fermeture du navigateur ou à l'exécution de la commande de déconnexion éventuelle. D'autres cookies \"survivent\" à la fermeture du navigateur et sont disponibles également lors de visites ultérieures de l'utilisateur. Ces cookies sont dits persistants et leur durée est fixée par le serveur au moment de leur création. Dans certains cas, une date d'expiration est fixée, dans d'autres cas, la durée est illimitée.",
    "testo_12" => "Gestion des cookies",
    "testo_13" => "L'utilisateur peut décider d'accepter ou non les cookies en utilisant les paramètres de son navigateur. Attention : la désactivation totale ou partielle des cookies techniques pourrait compromettre l'utilisation optimale du site. La désactivation des cookies \"tiers\" n'affecte en rien la navigabilité. Le paramètre peut être défini de manière spécifique pour les différents sites et applications web. De plus, les navigateurs permettent de définir des paramètres différents pour les cookies \"propriétaires\" et pour ceux de \"tiers\". Ce site peut incorporer des scripts sous forme de boutons ou de plugins pour faciliter le partage sur les réseaux sociaux. Ce site est intermédiaire pour les cookies de tiers sur lesquels il n'a pas de contrôle, il est donc nécessaire pour l'utilisateur de consulter les politiques de confidentialité directement sur les sites de référence des sociétés fournissant ces services.",
    "testo_14" => "À titre d'exemple, voici quelques liens :"
];