<?php

return [
    "titolo" => "Cookie-Richtlinie",
    "testo" => "Die Website!",
    "testo_2" => "verwendet technische Cookies, um das ordnungsgemäße Funktionieren der Verfahren sicherzustellen und die Benutzererfahrung bei der Nutzung der Online-Anwendungen zu verbessern. Dieses Dokument liefert Informationen über die Verwendung von Cookies und ähnlichen Technologien, wie sie von der Website verwendet werden und wie man sie verwaltet. Cookies sind kleine Textdateien, die die von den Nutzern besuchten Websites an ihre Geräte senden, wo sie gespeichert werden, um bei späteren Besuchen an dieselben Websites zurückgesendet zu werden. Cookies von 'Drittanbietern' hingegen werden von einer anderen Website als der, die der Benutzer gerade besucht, gesetzt. Dies liegt daran, dass jede Website Elemente (Bilder, Karten, Töne, spezifische Links zu Webseiten anderer Domains usw.) enthalten kann, die auf Servern gespeichert sind, die sich von dem Server der besuchten Website unterscheiden.",
    "testo_3" => "Arten von Cookies",
    "testo_4" => "Je nach Eigenschaften und Nutzung der Cookies können verschiedene Kategorien unterschieden werden:",
    "testo_5" => "Technische Cookies",
    "testo_6" => "Technische Cookies sind diejenigen, die ausschließlich dazu verwendet werden, \"die Übertragung einer Kommunikation über ein elektronisches Kommunikationsnetz durchzuführen oder in dem Maße, wie es für den Anbieter eines von dem Abonnenten oder Nutzer ausdrücklich angeforderten Informationsdienstes zur Bereitstellung dieses Dienstes unbedingt erforderlich ist\" (vgl. Art. 122, Abs. 1, des Gesetzes). Sie werden nicht für andere Zwecke verwendet und werden normalerweise direkt vom Betreiber oder Verwalter der Website installiert. Sie können in Navigations- oder Sitzungscookies unterteilt werden, die die normale Navigation und Nutzung der Website gewährleisten; Analytische Cookies, die den technischen Cookies gleichgestellt sind, wenn sie direkt vom Betreiber der Website verwendet werden, um Informationen in aggregierter Form über die Anzahl der Nutzer und deren Besuch der Website zu sammeln; Funktionale Cookies, die es dem Benutzer ermöglichen, basierend auf einer Reihe ausgewählter Kriterien zu navigieren, um den bereitgestellten Service zu verbessern. Für die Installation dieser Cookies ist keine vorherige Zustimmung der Nutzer erforderlich, während die Verpflichtung zur Information gemäß Art. 13 des Gesetzes, die der Betreiber der Website, falls er nur diese Geräte verwendet, auf die für ihn am besten geeignete Weise bereitstellen kann, in Kraft bleibt.",
    "testo_7" => "Profiling-Cookies",
    "testo_8" => "Profiling-Cookies dienen dazu, Profile des Nutzers zu erstellen und werden verwendet, um Werbenachrichten zu senden, die den beim Surfen geäußerten Präferenzen des Nutzers entsprechen. Aufgrund der besonderen Invasivität, die diese Geräte im privaten Bereich der Nutzer haben können, sieht die europäische und italienische Gesetzgebung vor, dass der Nutzer angemessen über deren Verwendung informiert wird und seine gültige Zustimmung erteilt. Dies bezieht sich auf Art. 122 des Gesetzes, der besagt, dass \"das Speichern von Informationen auf dem Endgerät eines Vertragspartners oder Nutzers oder der Zugriff auf bereits gespeicherte Informationen nur dann zulässig ist, wenn der Vertragspartner oder Nutzer nach Information in der vereinfachten Form gemäß Artikel 13, Absatz 3\" (Art. 122, Abs. 1, des Gesetzes) seine Zustimmung gegeben hat. Diese Website verwendet keine Profiling-Cookies.",
    "testo_9" => "Zur Überwachung und Verbesserung der Leistung der Website verwenden wir ein Marktstatistik-Produkt zur Erfassung von Zugriffsstatistiken. Es kann Cookies, sowohl permanente als auch nicht-permanente, verwenden, um statistische Informationen und über \"einzigartige Besucher\" der Website zu sammeln. Die Cookies, die als \"Unique Visitor Cookies\" definiert sind, enthalten einen alphanumerischen Code, der die Computer des Browsers identifiziert, ohne personenbezogene Daten zu sammeln.",
    "testo_10" => "Dauer der Cookies",
    "testo_11" => "Einige Cookies (Sitzungscookies) bleiben nur bis zum Schließen des Browsers oder bis zur Ausführung des Abmeldebefehls aktiv. Andere Cookies \"überleben\" das Schließen des Browsers und sind bei späteren Besuchen des Nutzers verfügbar. Diese Cookies werden als persistent bezeichnet und ihre Dauer wird vom Server bei ihrer Erstellung festgelegt. In einigen Fällen wird ein Ablaufdatum festgelegt, in anderen Fällen ist die Dauer unbegrenzt.",
    "testo_12" => "Cookie-Verwaltung",
    "testo_13" => "Der Nutzer kann entscheiden, ob er Cookies akzeptiert oder nicht, indem er die Einstellungen seines Browsers verwendet. Achtung: Das vollständige oder teilweise Deaktivieren technischer Cookies kann die optimale Nutzung der Website beeinträchtigen. Das Deaktivieren von \"Drittanbieter\"-Cookies beeinträchtigt das Surfen nicht. Die Einstellung kann spezifisch für verschiedene Websites und Webanwendungen definiert werden. Darüber hinaus ermöglichen es Browsern, unterschiedliche Einstellungen für \"eigene\" Cookies und \"Drittanbieter\"-Cookies zu definieren. Diese Website kann Skripte in Form von Schaltflächen oder Plugins integrieren, um das Teilen in sozialen Netzwerken zu erleichtern. Diese Website ist ein Vermittler für Drittanbieter-Cookies, über die sie keine Kontrolle hat, daher muss der Nutzer die Datenschutzerklärungen direkt auf den Referenzseiten der die Dienste erbringenden Unternehmen einsehen.",
    "testo_14" => "Beispielsweise einige Links:"
];