<?php

return [
    "titolo" => "Política de Cookies",
    "testo" => "¡El sitio web!",
    "testo_2" => "utiliza cookies técnicas para garantizar el correcto funcionamiento de los procedimientos y mejorar la experiencia de uso de las aplicaciones en línea. Este documento proporciona información sobre el uso de cookies y tecnologías similares, cómo se utilizan en el sitio y cómo gestionarlas. Las cookies son pequeños archivos de texto que los sitios visitados por los usuarios envían a sus dispositivos, donde se almacenan para luego ser retransmitidos a los mismos sitios en visitas posteriores. Las cookies denominadas 'de terceros', en cambio, son configuradas por un sitio web diferente al que el usuario está visitando. Esto se debe a que cada sitio puede contener elementos (imágenes, mapas, sonidos, enlaces específicos a páginas web de otros dominios, etc.) que residen en servidores diferentes al del sitio visitado.",
    "testo_3" => "Tipos de cookies",
    "testo_4" => "En función de las características y el uso de las cookies, se pueden distinguir diferentes categorías:",
    "testo_5" => "Cookies técnicas",
    "testo_6" => "Las cookies técnicas son aquellas utilizadas únicamente para \"transmitir una comunicación a través de una red de comunicación electrónica, o en la medida estrictamente necesaria para que el proveedor de un servicio de la sociedad de la información solicitado explícitamente por el abonado o usuario proporcione dicho servicio\" (véase el art. 122, párrafo 1, del Código). No se utilizan para otros fines y normalmente son instaladas directamente por el titular o el gestor del sitio web. Se pueden dividir en cookies de navegación o de sesión, que garantizan la navegación normal y el uso del sitio web; cookies analíticas, similares a las cookies técnicas cuando son utilizadas directamente por el gestor del sitio para recopilar información, de forma agregada, sobre el número de usuarios y cómo visitan el sitio; cookies de funcionalidad, que permiten al usuario navegar en función de una serie de criterios seleccionados para mejorar el servicio proporcionado. Para la instalación de estas cookies, no se requiere el consentimiento previo de los usuarios, mientras que la obligación de proporcionar información de acuerdo con el art. 13 del Código, que el gestor del sitio, si solo utiliza estos dispositivos, podrá proporcionar de la manera que considere más adecuada, sigue vigente.",
    "testo_7" => "Cookies de perfil",
    "testo_8" => "Las cookies de perfil tienen el objetivo de crear perfiles relativos al usuario y se utilizan para enviar mensajes publicitarios en línea con las preferencias expresadas por el usuario durante la navegación. Debido a la particular invasividad que estos dispositivos pueden tener en la esfera privada de los usuarios, la normativa europea e italiana exige que el usuario sea debidamente informado sobre su uso y dé su consentimiento válido. Esto se refiere al art. 122 del Código, que establece que \"el almacenamiento de información en el dispositivo terminal de un contratante o usuario o el acceso a información ya almacenada solo está permitido si el contratante o usuario ha dado su consentimiento después de haber sido informado de la manera simplificada prevista en el Artículo 13, párrafo 3\" (art. 122, párrafo 1, del Código). Este sitio no utiliza cookies de perfil.",
    "testo_9" => "Solo para monitorear y mejorar el rendimiento del sitio, utilizamos un producto de análisis estadístico para la detección de accesos al sitio. Puede usar cookies, tanto permanentes como no permanentes, para recopilar información estadística y sobre los \"visitantes únicos\" del sitio. Las cookies, definidas como \"Cookies de Visitante Único\", contienen un código alfanumérico que identifica las computadoras de navegación, sin recopilar datos personales.",
    "testo_10" => "Duración de las cookies",
    "testo_11" => "Algunas cookies (cookies de sesión) permanecen activas solo hasta el cierre del navegador o hasta la ejecución del comando de cierre de sesión. Otras cookies \"sobreviven\" al cierre del navegador y están disponibles durante visitas posteriores del usuario. Estas cookies se denominan persistentes, y su duración está fijada por el servidor en el momento de su creación. En algunos casos se fija una fecha de vencimiento, en otros casos, la duración es ilimitada.",
    "testo_12" => "Gestión de cookies",
    "testo_13" => "El usuario puede decidir si acepta o no las cookies utilizando la configuración de su navegador. Atención: la desactivación total o parcial de cookies técnicas podría comprometer el uso óptimo del sitio. La desactivación de cookies \"de terceros\" no afecta la navegabilidad. La configuración puede definirse de manera específica para diferentes sitios y aplicaciones web. Además, los navegadores permiten definir configuraciones diferentes para cookies \"de primera parte\" y para cookies \"de terceros\". Este sitio puede incorporar scripts en forma de botones o complementos para facilitar el compartir en redes sociales. Este sitio es intermediario para cookies de terceros sobre los que no tiene control, por lo que es necesario que el usuario consulte las políticas de privacidad directamente en los sitios de referencia de las empresas que proporcionan estos servicios.",
    "testo_14" => "A modo de ejemplo, aquí hay algunos enlaces:"
];